apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "self-service-copilot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-copilot.labels" . | nindent 4 }}
