apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alert-auto-investigator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alert-auto-investigator.labels" . | nindent 4 }}
