kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      receiver: warning
      group_by: ['alertname', 'priority']
      group_wait: 5s
      repeat_interval: 5m
      routes:
        - match:
            severity: warning
          receiver: warning
          #continue: true
        - match:
            severity: critical
          receiver: critical
        - match:
            severity: notice
          receiver: notice
          #continue: true
        # - match:
        #     severity: slack
        #   receiver: webhook
    receivers:
    # - name: alert-emailer
    #   email_configs:
    #   - to: fyu@health2sync.com
    #     send_resolved: false
    #     from: backend@health2sync.com
    #     smarthost: smtp.xxxx.com:25
    #     require_tls: false
    #
    - name: notice
      slack_configs:
      - api_url: https://hooks.slack.example.invalid/services/notice-webhook
        channel: '#server-report-dev'
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: '{{ template "slack.devops.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: '{{ template "slack.devops.text" . }}'
    - name: warning
      slack_configs:
      - api_url: https://hooks.slack.example.invalid/services/warning-webhook
        channel: '#devops-poc'
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: '{{ template "slack.devops.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: '{{ template "slack.devops.text" . }}'
    - name: critical
      slack_configs:
      - api_url: https://hooks.slack.example.invalid/services/critical-webhook
        channel: '#alarm-sla-critical'
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: '{{ template "slack.devops.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: '{{ template "slack.devops.text" . }}'
